#!/usr/bin/env python3

import argparse
from contextlib import contextmanager
import datetime
from itertools import chain, groupby, repeat
import logging
import math
import os
import pickle
import signal
import subprocess
import sys
import tempfile
import shutil

import numpy as np
import h5py

from scipy.interpolate import griddata
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt


"""
Modified to use MUSIC
"""


def run_cmd(*args):
    """
    Run and log a subprocess.

    """
    cmd = ' '.join(args)
    logging.info('running command: %s', cmd)

    try:
        proc = subprocess.run(
            cmd.split(), check=True,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            universal_newlines=True
        )
    except subprocess.CalledProcessError as e:
        logging.error(
            'command failed with status %d:\n%s',
            e.returncode, e.output.strip('\n')
        )
        return #raise
    else:
        logging.debug(
            'command completed successfully:\n%s',
            proc.stdout.strip('\n')
        )
        return proc


class Parser(argparse.ArgumentParser):
    """
    ArgumentParser that parses files with 'key = value' lines.

    """
    def __init__(self, *args, fromfile_prefix_chars='@', **kwargs):
        super().__init__(
            *args, fromfile_prefix_chars=fromfile_prefix_chars, **kwargs
        )

    def convert_arg_line_to_args(self, arg_line):
        # split each line on = and prepend prefix chars to first arg so it is
        # parsed as a long option
        args = [i.strip() for i in arg_line.split('=', maxsplit=1)]
        args[0] = 2*self.prefix_chars[0] + args[0]
        return args


parser = Parser(
    usage=''.join('\n  %(prog)s ' + i for i in [
        '[options] <results_folder>',
        'checkpoint <checkpoint_file>',
        '-h | --help',
    ]),
    description='''
Run relativistic heavy-ion collision events.

In the first form, run events according to the given options (below) and write
results to binary file <results_file>.

In the second form, run the event saved in <checkpoint_file>, previously
created by using the --checkpoint option and interrupting an event in progress.
''',
    formatter_class=argparse.RawDescriptionHelpFormatter
)


def parse_args_checkpoint():
    """
    Parse command line arguments according to the parser usage info.  Return a
    tuple (args, ic) where `args` is a normal argparse.Namespace and `ic` is
    either None or an np.array of the checkpointed initial condition.

    First, check for the special "checkpoint" form, and if found, load and
    return the args and checkpoint initial condition from the specified file.
    If not, let the parser object handle everything.

    This is a little hacky but it works fine.  Truth is, argparse can't do
    exactly what I want here.  I suppose `docopt` might be a better option, but
    it's not worth the effort to rewrite everything.

    """
    def usage():
        parser.print_usage(sys.stderr)
        sys.exit(2)

    if len(sys.argv) == 1:
        usage()

    if sys.argv[1] == 'checkpoint':
        if len(sys.argv) != 3:
            usage()

        path = sys.argv[2]

        try:
            with open(path, 'rb') as f:
                args, ic = pickle.load(f)
        except Exception as e:
            msg = '{}: {}'.format(type(e).__name__, e)
            if path not in msg:
                msg += ": '{}'".format(path)
            sys.exit(msg)

        # as a simple integrity check, require that the checkpoint file is
        # actually the file specified in the checkpointed args
        if os.path.abspath(path) != args.checkpoint:
            sys.exit(
                "checkpoint file path '{}' does not match saved path '{}'"
                .format(path, args.checkpoint)
            )

        return args, ic

    return parser.parse_args(), None


parser.add_argument(
    'results', type=os.path.abspath, metavar='PATH',
    help=argparse.SUPPRESS
)
parser.add_argument(
    '--buffering', type=int, default=0, metavar='INT',
    help='results file buffer size in bytes (default: no buffering)'
)
parser.add_argument(
    '--nevents', type=int, default=10, metavar='INT',
    help='number of events to run (default: run until interrupted)'
)
parser.add_argument(
    '--rankvar', metavar='VAR',
    help='environment variable containing process rank'
)
parser.add_argument(
    '--rankfmt', metavar='FMT',
    help='format string for rank integer'
)
parser.add_argument(
    '--tmpdir', type=os.path.abspath, metavar='PATH',
    help='temporary directory (default: {})'.format(tempfile.gettempdir())
)
parser.add_argument(
    '--checkpoint', type=os.path.abspath, metavar='PATH',
    help='checkpoint file [pickle format]'
)
parser.add_argument(
    '--particles', type=os.path.abspath, metavar='PATH',
    help='raw particle data file (default: do not save)'
)
parser.add_argument(
    '--logfile', type=os.path.abspath, metavar='PATH',
    help='log file (default: stdout)'
)
parser.add_argument(
    '--loglevel', choices={'debug', 'info', 'warning', 'error', 'critical'},
    default='info',
    help='log level (default: %(default)s)'
)
parser.add_argument(
    '--nucleon-width', type=float, default=.5, metavar='FLOAT',
    help='trento nucleon width [fm] (default: %(default)s fm)'
)
parser.add_argument(
    '--trento-args', default='Pb Pb', metavar='ARGS',
    help="arguments passed to trento (default: '%(default)s')"
)
parser.add_argument(
    '--tau-fs', type=float, default=.5, metavar='FLOAT',
    help='free streaming time [fm] (default: %(default)s fm)'
)
parser.add_argument(
    '--hydro-args', default='', metavar='ARGS',
    help='arguments passed to osu-hydro (default: empty)'
)
parser.add_argument(
    '--Tswitch', type=float, default=.150, metavar='FLOAT',
    help='particlization temperature [GeV] (default: %(default).3f GeV)'
)


class StopEvent(Exception):
    """ Raise to end an event early. """


def run_events(args, results_folder, checkpoint_ic=None):
    """
    Run events as determined by user input:

        - Read options from `args`, as returned by `parser.parse_args()`.
        - Write results to binary file object `results_file`.
        - If `checkpoint_ic` is given, run only that IC.

    Return True if at least one event completed successfully, otherwise False.

    """
    # set the grid step size proportionally to the nucleon width
    grid_step = .1
    # the "target" grid max: the grid shall be at least as large as the target
    grid_max_target = 25
    # next two lines set the number of grid cells and actual grid max,
    # which will be >= the target (same algorithm as trento)
    grid_n = math.ceil(2*grid_max_target/grid_step)
    grid_max = .5*grid_n*grid_step
    logging.info(
        'grid step = %.6f fm, n = %d, max = %.6f fm',
        grid_step, grid_n, grid_max
    )
    
    def _initial_conditions(nevents=10, initial_file='initial.hdf'):
        """
        Run trento and yield initial condition arrays.
    
        """
  #      try:
  #          os.remove(initial_file)
  #      except FileNotFoundError:
  #          pass
  
    
  #      run_cmd(
  #          'trento',
  #          '--number-events {}'.format(nevents),
  #          '--grid-step {} --grid-max {}'.format(grid_step, grid_max_target),
  #          '--output', initial_file,
  #          '--nucleon-width {}'.format(args.nucleon_width),
  #          args.trento_args
  #      )

        with h5py.File(initial_file, 'r') as f:
            for dset in f.values():
                ic = np.array(dset)

                if args.checkpoint is not None:
                    with open(args.checkpoint, 'wb') as cf:
                        pickle.dump((args,ic), cf, pickle.HIGHEST_PROTOCOL)
                    logging.info('wrote checkpoint file %s', args.checkpoint)
                yield ic
                
    
    if checkpoint_ic is None:
        # if nevents was specified, generate that number of initial conditions
        # otherwise generate indefinitely
        initial_conditions = (
            chain.from_iterable(_initial_conditions() for _ in repeat(None))
            if args.nevents is None else
            _initial_conditions(args.nevents)
        )
    else:
        # just run the checkpointed IC
        initial_conditions = [checkpoint_ic]


    def run_single_event(ic, event_number):
        """
        Run the initial condition event contained in HDF5 dataset object `ic`
        and save observables to `results`.

        """
        os.mkdir(str(event_number).zfill(int(np.floor(np.log10(args.nevents)))))
        os.chdir(str(event_number).zfill(int(np.floor(np.log10(args.nevents)))))

        with open('temp.dat', 'w') as f:
            f.write('# event \n')
            f.write('# b \n')
            f.write('# npart \n')
            f.write('# mult \n')
            f.write('# e2 \n')
            f.write('# e3 \n')
            f.write('# e4 \n')
            f.write('# e5 \n')
            for i in range(grid_n):
                newline = ''
                for j in range(grid_n):
                    newline += (str(ic[i,j]) + ' ')
                newline += '\n'
                f.write(newline)

        init_name = "trento_initial_condition_in_music_format.txt"

    #    if (os.path.isfile(init_name)):
    #        print("I'd rather not overwrite an existing file (\""+init_name+"\")... Aborting")
    #        exit(1)

        # Commands to convert Trento initial condition into the right grid format
                
        header_bash_command = "echo '# dummy 0.0 etamax= 1 xmax= "+str(grid_n)+" ymax= "+str(grid_n)+" deta= 10. dx= "+str(grid_step)+" dy= "+str(grid_step)+"' > "+init_name
        subprocess.run(header_bash_command, shell=True)

        conversion_bash_command="Ns=\""+str(grid_n)+"\"; tail -n+9 "+os.path.join("temp.dat") +" | perl -pe 's/\s+/\\n/g' | awk -v Ns=${Ns} 'BEGIN {for(x=0;x<Ns;x++){for(y=0;y<Ns;y++){T00[x+Ns*y]=0.0;}} Index=0;} {T00[Index]=$1; Index++;} END {for(x=0;x<Ns;x++){for(y=0;y<Ns;y++){print 0, (x-"+str(grid_n/2.)+")*"+str(grid_step)+","+"(y-"+str(grid_n/2.)+")*"+str(grid_step)+",T00[x+Ns*y],1,0,0,0, 0,0,0,0,0,0,0,0,0,0;} }}' >> "+init_name
        subprocess.run(conversion_bash_command, shell=True)

        os.system('rm temp.dat')

        run_cmd('~/music-eventgen/models/music-hydro/MUSIChydro ../music_input_trento') # Change directory if needed!

        os.chdir('../')

        return True

    nfail = 0

    for n, ic in enumerate(initial_conditions, start=1):
        logging.info('starting event %d', n)

        try: 
            run_single_event(ic,n)
        except StopEvent as e:
            logging.info('event stopped: %s', e)
        except Exception:
            logging.exception('event %d failed', n)
            nfail += 1
            #if nfail > 3 and nfail/n > 0.5:
            #    logging.critical('too many failures, stopping events')
            #    break
            logging.warning('continuing to next event')
            continue

        logging.info('event %d completed successfully', n)

    if args.checkpoint is not None:
        if checkpoint_ic is not None and nfail > 0:
            logging.info(
                'checkpoint event failed, keeping file %s',
                args.checkpoint
            )
        else:
            os.remove(args.checkpoint)
            logging.info('removed checkpoint file %s', args.checkpoint)
    
    return n > nfail


def main():
    args, checkpoint_ic = parse_args_checkpoint()

    if checkpoint_ic is None:
        # starting fresh -> truncate output files
        filemode = 'w'

        # must handle rank first since it affects paths
        if args.rankvar:
            rank = os.getenv(args.rankvar)
            if rank is None:
                sys.exit('rank variable {} is not set'.format(args.rankvar))

            if args.rankfmt:
                rank = args.rankfmt.format(int(rank))

            # append rank to path arguments, e.g.:
            #   /path/to/output.log  ->  /path/to/output/<rank>.log
            for a in ['logfile', 'checkpoint']:
                value = getattr(args, a)
                if value is not None:
                    root, ext = os.path.splitext(value)
                    setattr(args, a, os.path.join(root, rank) + ext)
    else:
        # running checkpoint event -> append to existing files
        filemode = 'a'

    os.makedirs(os.path.dirname(args.results), exist_ok=True)

    if args.logfile is None:
        logfile_kwargs = dict(stream=sys.stdout)
    else:
        logfile_kwargs = dict(filename=args.logfile, filemode=filemode)
        os.makedirs(os.path.dirname(args.logfile), exist_ok=True)

    if args.checkpoint is not None:
        os.makedirs(os.path.dirname(args.checkpoint), exist_ok=True)

    logging.basicConfig(
        level=getattr(logging, args.loglevel.upper()),
        format='[%(levelname)s@%(relativeCreated)d] %(message)s',
        **logfile_kwargs
    )
    logging.captureWarnings(True)

    start = datetime.datetime.now()
    if checkpoint_ic is None:
        logging.info('started at %s', start)
        logging.info('arguments: %r', args)
    else:
        logging.info(
            'restarting from checkpoint file %s at %s',
            args.checkpoint, start
        )

    # translate SIGTERM to KeyboardInterrupt
    signal.signal(signal.SIGTERM, signal.default_int_handler)
    logging.debug('set SIGTERM handler')

    results_folder = args.results

    @contextmanager
    def h5py_file():
        yield h5py.File(args.particles, 'w') if args.particles else None
        
    with tempfile.TemporaryDirectory(prefix='hic-', dir=args.tmpdir) as workdir:
        os.chdir(results_folder)
        logging.info('working directory: %s', results_folder)

        try:
            status = run_events(args, results_folder, checkpoint_ic)
        except KeyboardInterrupt:
            # after catching the initial SIGTERM or interrupt, ignore them
            # during shutdown -- this ensures everything will exit gracefully
            # in case of additional signals (short of SIGKILL)
            signal.signal(signal.SIGTERM, signal.SIG_IGN)
            signal.signal(signal.SIGINT, signal.SIG_IGN)
            status = True
            logging.info(
                'interrupt or signal at %s, cleaning up...',
                datetime.datetime.now()
            )
            if args.checkpoint is not None:
                logging.info(
                    'current event saved in checkpoint file %s',
                    args.checkpoint
                )

    end = datetime.datetime.now()
    logging.info('finished at %s, %s elapsed', end, end - start)

    if not status:
        sys.exit(1)


if __name__ == "__main__":
    main()
